---

- name: Install base packages
  apt:
    name: "{{ mail_base_pkgs }}"
    install_recommends: no
    update_cache: yes
  notify:
    - start services

- name: Create mailers group
  group:
    name: mailers

- name: Add Debian-exim to mailers group
  user:
    name: Debian-exim
    groups: [ 'mailers' ]
    append: yes
