---

- include: base.yml

- include: dkim.yml

- include: "{{ email_domain_ns_provider }}.yml"
  when: not email_ci

- include: molecule-dns.yml
  when: email_ci

- include: certbot.yml
  when: not email_ci

- include: custom_certs.yml
  when: email_certificates_path.certificate | length > 0 and
        email_certificates_path.key | length > 0

- include: exim.yml

- include: user.yml
  no_log: yes
  loop: "{{ email_users }}"

- include: dovecot.yml
