---
- name: update exim configuration
  shell: update-exim4.conf

- name: restart exim
  systemd:
    name: exim4
    state: restarted

- name: restart dovecot
  systemd:
    name: dovecot
    state: restarted

- name: start services
  systemd:
    name: exim4
    state: restarted
    enabled: yes
  loop:
    - exim4
    - dovecot
