---

- name: Converge
  hosts: all
  vars:
    email_server_external_ip: "{{ ansible_default_ipv4.address }}"
    email_ci: true
    email_domain_zone: molecule.local
    email_users:
      - name: molecule_no_quota
        password: molecule
      - name: molecule_quota
        password: molecule
        quota: 1
    email_certificates_path:
      certificate: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/files/mail.{{ email_domain_zone }}.crt"
      key: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/files/mail.{{ email_domain_zone }}.crt"
  roles:
    - ansible-role-email
