---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: mail
    image: jrei/systemd-debian:10
    pre_build_image: true
    registry:
      url: docker.io
    networks:
      - name: molecule.local
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
