name: Molecule
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
          fetch-depth: 0
      - uses: gofrolist/molecule-action@v2.0.2
        with:
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.scenario }}
